const express = require("express")
const cors = require("cors")
const bodyParser = require("body-parser")
const { connectDatabase } = require("./config/databaseConfig")
const UserRouter = require("./Routers/User.js")
const HospitalRouter = require("./Routers/Hospital.js")
const DoctorRouter = require("./Routers/Doctor.js")
const app = express()
let port = process.env.PORT || 5000
app.use(cors())
app.use(bodyParser.urlencoded({ extended: true, limit: "25mb" }))
app.use(bodyParser.json())
connectDatabase()
app.use("/user", UserRouter)
app.use("/hospital", HospitalRouter)
app.use("/doctor", DoctorRouter)
app.listen(port, () => {
    console.log(`Server is running on port ${port}`)
})